name: Create Release and Update Repository

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: Lunatory/DalamudRepo/.github/workflows/reusable_create_release.yml@master
    with:
      internal_name: AetherBags
      solution_name: AetherBags
      build_configuration: x64/Release
      personal_plugin_repo: Lunatory/DalamudRepo
      personal_plugin_repo_branch: master
    secrets: inherit
